name: 'Publish Weni Protobuffers in Pypi'
on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Source branch (only branches inherited from main)'
        required: true
      package-version:
        description: 'Package Version (2.0.0-alpha.0, 2.0.0-alpha.2, ...)'
jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 'Check out the repo'
        uses: actions/checkout@v2
        with:
          repository: Ilhasoft/weni-protobuffers
          ref: ${{github.event.inputs.source-branch}}
      - working-directory: ./python
      - name: 'Install Poetry'
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: 'Print Versão'
        run: poetry version && ls
      - name: 'Update poetry version'
        run: poetry version ${{github.event.inputs.package-version}}
      - name: 'Print Versão Depois'
        run: poetry version && ls
